POST http://localhost:3001/api/products
Content-Type: application/json

{
    "numeroReferencia": "300-REf",
    "nombre": "Shampoo",
    "categoria": "cabello",
    "cantidad": 200,
    "precio": 0,
    "ubicacion": "2-A-c"
}